name: Build
on: [push, pull_request]

jobs:
  build:
    runs-on: windows-latest
    steps:
      # Prepare
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: gittools/actions/gitversion/setup@v0.9.15
        with:
          versionSpec: '5.11.x'
      - uses: gittools/actions/gitversion/execute@v0.9.15
        id: gitversion

      # Build
      - name: Build (pre-release)
        if: steps.gitversion.outputs.preReleaseLabel != ''
        run: .\build.ps1 ${{steps.gitversion.outputs.nuGetVersion}}-${{steps.gitversion.outputs.shortSha}}
      - name: Build (release)
        if: steps.gitversion.outputs.preReleaseLabel == ''
        run: .\build.ps1 ${{steps.gitversion.outputs.nuGetVersion}}

      # Release
      - name: Create GitHub Release
        if: steps.gitversion.outputs.preReleaseLabel == ''
        uses: softprops/action-gh-release@v1

      # Publish
      - name: Publish packages (GitHub)
        if: github.event_name == 'push'
        run: |
          Get-ChildItem artifacts\Release\*.nupkg | ForEach-Object {
            curl.exe -sS -X PUT -u "${{github.actor}}:${{github.token}}" -F package=@$_ https://nuget.pkg.github.com/${{github.repository_owner}}/
          }
      - name: Publish packages (NuGet.org)
        if: steps.gitversion.outputs.preReleaseLabel == ''
        run: dotnet nuget push artifacts\Release\*.nupkg --source nuget.org --api-key ${{secrets.NUGET_API_KEY}}
